### PR TITLE
Improvements in README 

### PR DESCRIPTION
**Pull request by vonhoff**
Improvements made:

1. Replaced the previous screenshot with an actual screenshot from the Clove101Example project running on Ubuntu. 
(The previous one was slightly edited to make it look like there were 2 digits. This resulted in two different fonts).
2. Fixed typos
   * boilder-plate => boilerplate
   * greather => greater
   * as follow => as follows
   * retrive => retrieve
   * availables => available
   * lanched => launched
   * choises => choices
   * succesfully => successfully
   * valids => valid
   * fuction => function
3. Fixed references to example files
   * (./examples/clove101/test_suite1.c) => (./examples/clove101/**src**/test_suite1.c)
   * (./examples/clove101/test_suite2.c) => (./examples/clove101/**src**/test_suite2.c)
4. Reformatted tables

### CODE REVIEW

**Comment by fdefelici** [comment]
@vonhoff thanks for double checking the Readme.
Anyhow I don't see changes on Readme (just the png). Did you push the README.md file?

PS: I have updated readme when merging for #65  (just touched the Assertion APIs table), so don't know if some conflict need to be addressed

**Comment by vonhoff** [comment]
I haven't pushed it yet, as I'm still improving it. I will mark this PR as ready once I pushed the improvements.

**Comment by vonhoff** [comment]
1. Fixed broken Conan link.
2. Fixed grammar (e.g., added punctuation).
3. Added a simple table of contents.
4. Rephrased a few sentences.

Please let me know if something has to be changed.

**Comment by fdefelici** [comment]
Small Review:
- on Table Contents
- Usage paragraphs
- Removed comma from Assertions to be simmetric with other api doc that works like a "method" call.

@vonhoff let me know if we are fine :)

**Comment by fdefelici** [comment]
Probably before merging, I'll do one more edit in the readme to list a discord server dedicated to clove-unit and related plugins that I'm going to create next days.

**Comment by vonhoff** [comment]
Sounds good to me, the last commit I pushed contains a slight grammar fix with table formatting.

The verb 'set up' is spelled as two words. The noun 'setup' is spelled as one. 

- Incorrect:  They setup a meeting. 
- Correct:  They set up a meeting.

**Comment by fdefelici** [comment]
Small paragraph renaming:
- Usage => Getting Started
- Development API => Programming API
- IDE Extension => IDE Extensions

Add Discord channel badge

Restored previous sample image who has better font sizing and color contrast

**Comment by fdefelici** [comment]
@vonhoff discord server is up and running. If you want you are invited :)

Server Name: CLove-Unit
Invite: https://discord.gg/XV8kQg7Q

**Pull request merged**
