### PR TITLE
Align test counter

### LINKED ISSUE #42: RunTest Pretty Print: Align test counter
Currently test counter is like this:
```
[INFO] 9) UNIT_StringViewTest.Contains.............................[PASS] (0.011 ms)
[INFO] 99) UNIT_StringViewTest.AsString............................[PASS] (0.011 ms)
[INFO] 100) UNIT_StringViewTest.BeginAndEnd........................[PASS] (0.001 ms)
```
It could become like this:
```
[INFO] 009) UNIT_StringViewTest.Contains...........................[PASS] (0.011 ms)
[INFO] 099) UNIT_StringViewTest.AsString...........................[PASS] (0.011 ms)
[INFO] 100) UNIT_StringViewTest.BeginAndEnd........................[PASS] (0.001 ms)
```

So '0' left padding to reach same length of the highest test number.

NOTE: Update reference image (pretty print) in Readme

### PR DESCRIPTION
**Pull request by vonhoff**
Fix #42

### CODE REVIEW

**Review by fdefelici — COMMENTED** [review]
Not sure if this could work properly (some unit integration/unit test are missing to verify this scenario).
IMHO, it seems the max test number calculation is specific for each suite. Instead, a proper alignement we need the overall test count. (Imagine a test suite with 1 test and another test suite with 9 test. The overall count is 10, so all tests need to be aligned with 2 digits).

The overall test count is collected in this method and passed to the report in the start method
image

Maybe instead of add one more param to the __clove_exec_suite, we could store the test_count as a member of the pretty print report "object" when executing __clove_report_pretty_start. 
Futhermore we could also precompute the number of digits and store it also as member 
for reuse later in the  ___clove_report_pretty_end_test.

**Comment by vonhoff** [comment]
I agree that using the total test count is better for proper alignment in the report. I think we could add the total number of digits for the test counter as a member for `__clove_test_t` for later reuse, I applied these refinements and added relevant unit tests.
Perhaps it might be a better idea to add this member to each suite, what do you think?

**Comment by vonhoff** [comment]
Just had a thought, another way to calculate the number of digits in a number is to use the following formula: `(int)log10(number) + 1`. 

Currently it uses the return value of `snprintf`, but I'm not yet sure which method is more efficient.

**Comment by fdefelici** [comment]
> I agree that using the total test count is better for proper alignment in the report. I think we could add the total number of digits for the test counter as a member for `__clove_test_t` for later reuse, I applied these refinements and added relevant unit tests.
> Perhaps it might be a better idea to add this member to each suite, what do you think?

From the design pov neigher test not suite should be coupled with the overall test count. Infact this information is required just for report purposes (like the  test enumeration count).

So on this, better to follow what has been shared on the first review (storing max digit number when call report start)

**Comment by fdefelici** [comment]
> Just had a thought, another way to calculate the number of digits in a number is to use the following formula: `(int)log10(number) + 1`. 
> 
> Currently it uses the return value of `snprintf`, but I'm not yet sure which method is more efficient.

Well, performance wise doesnt really matter in our case. Instead I would prefer the log10 solution because avoid involving "strings" for the calculation, and probably is more explicative.

Probably finally result could be a uint.

**Comment by vonhoff** [comment]
Seems like the build fails on ubuntu because it cannot find log10, not sure why as `math.h` is included at line 2149. Might try the first solution with `snprintf` otherwise. I will have a look at it tonight.

**Comment by vonhoff** [comment]
It's related to a linking error, found this about the math.h: https://askubuntu.com/a/332919
I think adding `-lm` to [workflows/ci_action.yml#L26](https://github.com/fdefelici/clove-unit/blob/d43981b346bfe374cbff6958092daa72aa2611c4/.github/workflows/ci_action.yml#L26) might solve this issue.

**Comment by fdefelici** [comment]
> Seems like the build fails on ubuntu because it cannot find log10, not sure why as `math.h` is included at line 2149. Might try the first solution with `snprintf` otherwise. I will have a look at it tonight.

Yeah, probably because with math api used, like fabsf, compiler receive just costants by unit tests and make some optimization avoiding real call to that api.
Eventually you could also try forcing fabsf to behave at runtime using some random calculated value or similar. (I would do it myself, but I have my period off and I dont have a computer with me. Just the mobile phone and even doing code review is hard as hell :))

After that we could decide about the linkage parameter for gcc.

**Comment by vonhoff** [comment]
> Yeah, probably because with math api used, like fabsf, compiler receive just costants by unit tests and make some optimization avoiding real call to that api. Eventually you could also try forcing fabsf to behave at runtime using some random calculated value or similar. (I would do it myself, but I have my period off and I dont have a computer with me. Just the mobile phone and even doing code review is hard as hell :))
> 
> After that we could decide about the linkage parameter for gcc.

That could work, I updated the float and double comparison tests to use random volatile variables to avoid compiler optimizations. This would also ensure real-time behavior.

**Comment by fdefelici** [comment]
Strange, it seems only log10 api is affected by misses linkage.

Ww can rollback the last test to the previous non-random implementation and also rollback to snprintf implementation for counting digits (this preserve backward compilation compatibility for the ones using clove on unix system without using -lm)

Or if you have other ideas, I'm all ears :)

**Comment by vonhoff** [comment]
Pushed it, it should work now.

**Comment by fdefelici** [comment]
Ok. Compilation seems fine.

Last thing: better to explict (unsigned int) cast to snprintf (that returns int), just to avoid compilation warning or error in case user set specific flags.

**Pull request merged**
